'use strict'
// The pure-node FLAC Vorbis-comment writer (W2-UI contract: tagWriteBatch, and
// roadmap #9's write-back). Round-trips against a REAL FLAC fixture generated by
// ffmpeg (test/fixtures/tag-sample.flac), so the byte layout being exercised is
// a genuine FLAC stream, not one this code also produced.
const test = require('node:test')
const assert = require('node:assert')
const fs = require('fs')
const os = require('os')
const path = require('path')

const flac = require('../src/flac-tags')

const FIXTURE = path.join(__dirname, 'fixtures', 'tag-sample.flac')

function tmpCopy() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'papa-flac-'))
  const p = path.join(dir, 'sample.flac')
  fs.copyFileSync(FIXTURE, p)
  return p
}

test('reads the existing comments from a real FLAC', () => {
  const map = flac.readComments(fs.readFileSync(FIXTURE))
  assert.strictEqual(map.GENRE, 'rock')
  assert.strictEqual(map.TITLE, 'Original Title')
})

test('writeFileTags round-trips every contract field', () => {
  const p = tmpCopy()
  const r = flac.writeFileTags(p, {
    genre: 'Jazz', title: 'New Title', artist: 'Miles',
    album: 'Kind of Blue', year: '1959',
  })
  assert.deepStrictEqual(r, { ok: true })
  const map = flac.readComments(fs.readFileSync(p))
  assert.strictEqual(map.GENRE, 'Jazz')
  assert.strictEqual(map.TITLE, 'New Title')
  assert.strictEqual(map.ARTIST, 'Miles')
  assert.strictEqual(map.ALBUM, 'Kind of Blue')
  assert.strictEqual(map.DATE, '1959')   // year is stored under DATE
})

test('a rewrite preserves the audio frames (still a valid, non-empty FLAC)', () => {
  const p = tmpCopy()
  const before = fs.readFileSync(p)
  flac.writeFileTags(p, { title: 'X' })
  const after = fs.readFileSync(p)
  // The audio is the tail after the metadata; both parse cleanly and the audio
  // region is byte-identical, which is the whole point of a lossless tag edit.
  const pa = flac._parseBlocks(before)
  const pb = flac._parseBlocks(after)
  assert.ok(before.slice(pa.audioStart).equals(after.slice(pb.audioStart)),
    'audio frames must be untouched by a tag write')
  assert.ok(after.length > 0)
})

test('writing an existing field replaces it rather than duplicating', () => {
  const p = tmpCopy()
  flac.writeFileTags(p, { genre: 'Jazz' })   // fixture already has GENRE=rock
  const buf = fs.readFileSync(p)
  const parsed = flac._parseBlocks(buf)
  let vorbisBody = null
  for (const b of parsed.blocks) if (b.type === 4) vorbisBody = b.body
  const v = flac._parseVorbis(vorbisBody)
  const genres = v.comments.filter(c => c.key.toUpperCase() === 'GENRE')
  assert.strictEqual(genres.length, 1, 'exactly one GENRE entry, not a duplicate')
  assert.strictEqual(genres[0].value, 'Jazz')
})

test('an empty-string value clears the field', () => {
  const p = tmpCopy()
  flac.writeFileTags(p, { genre: '' })
  const map = flac.readComments(fs.readFileSync(p))
  assert.strictEqual(map.GENRE, undefined)
})

test('the write uses temp-write-rename: no temp file left behind', () => {
  const p = tmpCopy()
  const dir = path.dirname(p)
  flac.writeFileTags(p, { title: 'Clean' })
  const leftovers = fs.readdirSync(dir).filter(n => n.startsWith('.papa-flac-'))
  assert.deepStrictEqual(leftovers, [])
})

test('writeBatch skips non-FLAC with reason unsupported and reports written', () => {
  const p = tmpCopy()
  const mp3 = path.join(path.dirname(p), 'x.mp3')
  fs.writeFileSync(mp3, 'not flac')
  const res = flac.writeBatch([
    { filePath: p, changes: { genre: 'Soul' } },
    { filePath: mp3, changes: { genre: 'Soul' } },
  ])
  assert.strictEqual(res.written, 1)
  assert.deepStrictEqual(res.skipped, [{ filePath: mp3, reason: 'unsupported' }])
})

test('writeBatch honours the guard, skipping refused paths', () => {
  const p = tmpCopy()
  const res = flac.writeBatch(
    [{ filePath: p, changes: { title: 'Nope' } }],
    () => false,   // guard rejects everything
  )
  assert.strictEqual(res.written, 0)
  assert.deepStrictEqual(res.skipped, [{ filePath: p, reason: 'refused' }])
})

test('a non-FLAC file with a .flac extension is skipped, not corrupted', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'papa-flac-'))
  const fake = path.join(dir, 'fake.flac')
  fs.writeFileSync(fake, 'ID3 this is not a flac')
  const res = flac.writeFileTags(fake, { genre: 'x' })
  assert.strictEqual(res.ok, false)
  assert.strictEqual(res.reason, 'unsupported')
  // Untouched.
  assert.strictEqual(fs.readFileSync(fake, 'utf8'), 'ID3 this is not a flac')
})

test('unknown change fields are ignored, not written as junk keys', () => {
  const p = tmpCopy()
  flac.writeFileTags(p, { title: 'T', bogusField: 'should not appear' })
  const map = flac.readComments(fs.readFileSync(p))
  assert.strictEqual(map.TITLE, 'T')
  assert.ok(!('BOGUSFIELD' in map))
})
