'use strict'
// V1 wiring: the deck uses the motion module for release physics, the corner
// grip, the theatre↔card flight, the hover chrome, and the keys that reach a
// minimised card; the geometry accepts a free width.
const test = require('node:test')
const assert = require('node:assert')
const fs = require('node:fs')
const path = require('node:path')
const SRC = path.join(__dirname, '..', 'src')
const DECK = fs.readFileSync(path.join(SRC, 'video-player.js'), 'utf8')
const PROXY = fs.readFileSync(path.join(SRC, 'web-player.js'), 'utf8')
const HTML = fs.readFileSync(path.join(SRC, 'index.html'), 'utf8')
const CSS = fs.readFileSync(path.join(SRC, 'styles.css'), 'utf8')
const { miniVideoDims, sanitizeMiniPos, MINI } = require('../src/video-player')

test('a free width is a valid size: 16:9, clamped, persisted; junk still degrades to compact', () => {
  assert.deepEqual(miniVideoDims(400), { w: 400, h: 225 })
  assert.deepEqual(miniVideoDims(5000), { w: MINI.maxW, h: Math.round(MINI.maxW * 9 / 16) })
  assert.deepEqual(miniVideoDims(10), { w: MINI.minW, h: Math.round(MINI.minW * 9 / 16) })
  assert.deepEqual(sanitizeMiniPos({ corner: 'tl', size: 412.6 }), { corner: 'tl', size: 413 })
  assert.deepEqual(sanitizeMiniPos({ corner: 'tl', size: 99999 }), { corner: 'tl', size: 'compact' })
  assert.deepEqual(sanitizeMiniPos({ corner: 'tl', size: 'huge' }), { corner: 'tl', size: 'compact' })
})

test('release: the drop point is projected along the release velocity, then the card settles on the spring', () => {
  const end = DECK.slice(DECK.indexOf('const endDrag = function'), DECK.indexOf('// The picture region joins the drag surfaces'))
  assert.match(end, /motion\.velocity\(samples, nowMs\(\)\)/)
  assert.match(end, /motion\.projectedPoint\(from, v\)/)
  assert.match(end, /nearestCorner\(aim,/)
  assert.match(end, /settleTo\(from, v\)/)
  const settle = DECK.slice(DECK.indexOf('function settleTo('), DECK.indexOf('function mini_setSettling('))
  assert.match(settle, /lessMotion\(\)\) \{ placeMiniCard\(null, true\); return \}/, 'less motion means a plain snap')
  assert.match(settle, /if \(p\.done\) \{[^}]*placeMiniCard\(null, true\)/, 'the last frame is the persisted anchor')
  assert.match(DECK, /const live = stopSettle\(\)\n\s+baseTL = live \|\|/, 'grabbing a settling card picks it up where it is')
})

test('the corner grip resizes freely and grows away from the anchored corner', () => {
  assert.match(HTML, /id="vmini-resize"/)
  const rs = DECK.slice(DECK.indexOf('function bindMiniResize('), DECK.indexOf('function bindMiniDrag('))
  assert.match(rs, /motion\.resizedWidth\(startW, e\.clientX - sx, e\.clientY - sy, miniPos\.corner, cap\)/)
  assert.match(rs, /saveMiniPos\(\)/)
  assert.match(DECK, /mini\.dataset\.corner = miniPos\.corner/)
  for (const c of ['tl', 'tr', 'bl', 'br']) assert.match(CSS, new RegExp('\\.vmini\\[data-corner="' + c + '"\\] \\.vmini-resize \\{'))
  assert.match(DECK, /mini\.style\.setProperty\('--vmini-w', dims\.w \+ 'px'\)/)
  assert.match(CSS, /width:var\(--vmini-w, var\(--vmini-w-compact\)\)/)
})

test('minimise measures the stage before hiding the theatre and flies the card; restore flies back and re-seats the picture on landing', () => {
  const mini = DECK.slice(DECK.indexOf('function minimise()'), DECK.indexOf('function restore()'))
  assert.ok(mini.indexOf('flightStageRect()') < mini.indexOf("root.classList.add('hidden')"), 'measure first')
  assert.match(mini, /placeMiniCard\(null, true\)\n[^\n]*\n[^\n]*\n\s+flyCard\(stageRect, false\)/)
  const rest = DECK.slice(DECK.indexOf('function restore()'), DECK.indexOf('function flightStageRect()'))
  assert.match(rest, /const willFly = wasPip && canFly\(\)\n\s+if \(!willFly && mini\) mini\.classList\.add\('hidden'\)/)
  assert.match(rest, /flight\.then\(land, land\)/)
  const fly = DECK.slice(DECK.indexOf('function canFly()'), DECK.indexOf("let closing = false"))
  assert.match(fly, /pictureInPage\(\) && !lessMotion\(\) && typeof mini\.animate === 'function'/)
  assert.match(fly, /const ghost = makeGhost\(dims\)/, 'a snapshot flies, not the live video')
  assert.match(fly, /motion\.flipKeyframes\(stageRect, \{ x: anchor\.x, y: anchor\.y \+ MINI\.handleH \}, dims, 0\)/)
  assert.match(CSS, /\.vmini\.vmini-flying \{ animation:none; visibility:hidden; \}/)
  assert.match(PROXY, /proxy\.videoRenderPath = function \(\) \{ return active\(\) \? 'web' : 'native' \}/)
  assert.match(CSS, /\.vmini \{[^}]*transform-origin:0 0;/)
})

test('hover chrome on the picture and keys that reach a minimised card', () => {
  for (const id of ['vmini-ov-play', 'vmini-ov-open', 'vmini-ov-close']) assert.match(HTML, new RegExp('id="' + id + '"'))
  assert.match(DECK, /\$\('vmini-ov-play'\)\?\.addEventListener\('click', togglePlay\)/)
  assert.match(DECK, /\$\('vmini-ov-open'\)\?\.addEventListener\('click', restore\)/)
  assert.match(CSS, /\.vmini:hover \.vmini-overlay, \.vmini:focus-within \.vmini-overlay \{ opacity:1; pointer-events:auto; \}/)
  assert.match(CSS, /\.vmini\.vmini-dragging \.vmini-overlay[^{]*\{ opacity:0; pointer-events:none; \}/)
  const key = DECK.slice(DECK.indexOf('function onKey(e)'), DECK.indexOf('let isFullscreen = false'))
  assert.match(key, /if \(!minimised \|\| !state \|\| isTypingTarget\(e\.target\)\) return/)
  assert.match(key, /if \(!onCard\) return/, 'keys reach the card only while it has focus')
  assert.match(key, /if \(hit\.action === 'exit'\) \{ if \(active && typeof active\.blur === 'function'\) active\.blur\(\) \}/, 'Escape hands the keyboard back')
  assert.match(HTML, /id="vmini" class="vmini hidden" role="region" aria-label="Now playing" tabindex="-1"/, 'a click can focus the card')
  const RENDERER = fs.readFileSync(path.join(SRC, 'renderer.js'), 'utf8')
  assert.match(RENDERER, /e\.target\.closest\('#vmini'\) &&\n\s+!e\.ctrlKey && !e\.altKey && !e\.metaKey\) return/, 'the music shortcuts stand down while the card has focus')
  const grid = RENDERER.slice(RENDERER.indexOf('if (!VIDEO_PAGES.has(page)) return'), RENDERER.indexOf('function _moveCardFocus('))
  assert.match(grid, /e\.target\.closest\('#vmini'\)\) return/, 'the poster-grid arrows stand down too')
  assert.match(key, /if \(hit\.action === 'fullscreen'\) restore\(\)/)
})
